# Dependabot will run on day 28 of each month at 01:23 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "23 1 28 * *"
    open-pull-requests-limit: 20
    assignees:
      - "hausbusde"
    versioning-strategy: "increase"
